apiVersion: v1
kind: ServiceAccount
metadata:
  name: promtail-serviceaccount
  namespace: thingsboard
---
apiVersion: v1
kind: Service
metadata:
  name: promtail-service
  namespace: thingsboard
  annotations:
    promtail.io/scrape: 'true'
    promtail.io/port:   '9080'
spec:
  selector:
    app: promtail-server
  type: ClusterIP
  ports:
  - port: 9080
    name: http