apiVersion: v1
kind: ServiceAccount
metadata:
  name: promtail-serviceaccount
  namespace: thingsboard
---
apiVersion: v1
kind: Service
metadata:
  name: promtail-service
  namespace: thingsboard
  annotations:
    promtail.io/scrape: 'true'
    promtail.io/port:   '9080'
spec:
  # selector:
  #   app: promtail-server
  # type: NodePort
  # ports:
  #   - port: 9080
  #     targetPort: 9080
  #     nodePort: 30080
  selector:
    app: promtail-server
  type: ClusterIP
  ports:
  - port: 9080
    name: http