apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
  namespace: thingsboard
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    app: prometheus-server
  ports:
    - port: 80
      targetPort: 9090
      name: http
---
