apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: backup-viewer-pod
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: busybox
    spec:
      containers:
        - name: backup-viewer-pod
          image: pon0mar/k8s-backup
          imagePullPolicy: Always
          command:
            - /bin/bash
            - -c
            - sleep 25000000
          volumeMounts:
            - name: cassandra-data
              mountPath: /var/lib/cassandra
            - name: datastore
              mountPath: /data
            - name: s3cfg
              mountPath: /s3
              readOnly: false
        volumes:
          - name: cassandra-data
            persistentVolumeClaim:
              claimName: cassandra-data-cassandra-0
          - name: datastore
            persistentVolumeClaim:
              claimName: tb-backup-cassandra-cassandra-0

        restartPolicy: OnFailure