apiVersion: v1
kind: Pod
metadata:
  name: s3-backup-cassandra
  namespace: thingsboard
spec:
  nodeSelector:
    role: cassandra
    cassandraNode: "1"
  containers:
  - name: s3-backup-cassandra
    image: YOUR_DOCKERHUB_NAME/k8s-backup
    imagePullPolicy: Always
    env:
      - name: WEBHOOK
        value: YOUR_WEBHOOK_ENDPOINT
      - name: S3_BUCKET_URI
        value: YOUR_S3_BUCKET_URI
      - name: CQLSH_HOST
        value: cassandra
      - name: DB
        value: /var/lib/cassandra/data/thingsboard/
      - name: DATASTORE
        value: /data
    command:
      - /bin/bash
      - -c
      - /home/root/backupCassandraToS3.sh && sleep 250000
    volumeMounts:
      - name: cassandra-data
        mountPath: /var/lib/cassandra
      - name: datastore
        mountPath: /data
      - name: s3cfg
        mountPath: /s3
        readOnly: false
  volumes:
    - name: cassandra-data
      persistentVolumeClaim:
        claimName: cassandra-data-cassandra-0
    - name: datastore
      persistentVolumeClaim:
        claimName: tb-backup-cassandra-cassandra-0
    - name: s3cfg
      configMap:
        name: s3-cfg
        defaultMode: 0755

  restartPolicy: OnFailure

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: s3-cfg
data:
  s3cfg: |+
    [default]
    host_base = s3.amazonaws.com
    host_bucket = 
    check_ssl_certificate = False
    use_https = True
    cloudfront_host = cloudfront.amazonaws.com
    access_key = 
    secret_key = 
---
