apiVersion: v1
kind: Service
metadata:
  name: alertmanager
  namespace: thingsboard
  annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/port:   '9093'
# spec:
#   selector: 
#     app: alertmanager
#   type: NodePort  
#   ports:
#     - port: 9093
#       targetPort: 9093
#       nodePort: 31000

spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    app: alertmanager
  ports:
    - port: 80
      targetPort: 9093
      name: alertmanager