apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: exporter
    app.kubernetes.io/name: kube-state-metrics
    app.kubernetes.io/version: 2.3.0
  name: kube-state-metrics
  namespace: kube-system
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    app.kubernetes.io/name: kube-state-metrics
  ports:
  -  name: http-metrics
     port: 80
     targetPort: http-metrics
  -  name: telemetry
     port: 81
     targetPort: telemetry

  # clusterIP: None
  # ports:
  # - name: http-metrics
  #   port: 8080
  #   targetPort: http-metrics
  # - name: telemetry
  #   port: 8081
  #   targetPort: telemetry
  # selector:
  #   app.kubernetes.io/name: kube-state-metrics