apiVersion: v1
kind: Pod
metadata:
  name: s3-backup-cassandra
  namespace: thingsboard
spec:

  containers:
  - name: cass-to-s3
    # image: alpine/k8s:1.22.6
    image: pon0mar/k8s-backup
    imagePullPolicy: Always
    env:
      - name: WEBHOOK
        value: YOUR_WEBHOOK_ENDPOINT
      - name: S3_BUCKET_URI
        value: YOUR_S3_BUCKET_URI
      - name: CQLSH_HOST
        value: cassandra
    command:
      - /bin/bash
      - -c
      - /home/root/backupCassandraToS3.sh && sleep 250000
    volumeMounts:
      - name: cassandra-data
        mountPath: /var/lib/cassandra
      - name: datastore
        mountPath: /data
      - name: s3cfg
        mountPath: /s3
        readOnly: false
  volumes:
    - name: cassandra-data
      persistentVolumeClaim:
        claimName: cassandra-data-cassandra-1
    - name: datastore
      persistentVolumeClaim:
        claimName: tb-backup-cassandra-cassandra-1
    - name: s3cfg
      configMap:
        name: s3-cfg
        defaultMode: 0755

  restartPolicy: OnFailure

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: s3-cfg
data:
  s3cfg: |+
    [default]
    host_base = s3.amazonaws.com
    host_bucket = tbandrii.s3.eu-central-1.amazonaws.com
    check_ssl_certificate = False
    use_https = True
    cloudfront_host = cloudfront.amazonaws.com
    access_key = AKIAVQI7XYHZWDO3IKX5
    secret_key = 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
---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: tb-backup-cassandra
# spec:
#   accessModes:
#     - ReadWriteMany
#   resources:
#     requests:
#       storage: 4Gi